#!/usr/bin/env bash

cc=clang
cflags=-Wall

echo Gathering source files...
source_files=
for file in $(find $(pwd)/src/ -type f)
do
    source_files="$source_files $file"
done

if [ ! -d ./bin ]; then
   mkdir bin
   echo Created bin/
fi

pushd bin/ > /dev/null # Piping into /dev/null to silence output
$cc $cflags -c $source_files
popd > /dev/null
